import Icon from "./Icon";
import type { IconProps } from "./types";
export const Caution = (props: IconProps) => <Icon {...props} name="caution" />;
export const CheckCircle = (props: IconProps) => <Icon {...props} name="check-circle" />;
export const ChevronDown = (props: IconProps) => <Icon {...props} name="chevron-down" />;
export const ChevronUp = (props: IconProps) => <Icon {...props} name="chevron-up" />;
export const Close = (props: IconProps) => <Icon {...props} name="close" />;
export const Dashboard = (props: IconProps) => <Icon {...props} name="dashboard" />;
export const Moon = (props: IconProps) => <Icon {...props} name="moon" />;
export const ScoreTrends = (props: IconProps) => <Icon {...props} name="score-trends" />;
export const Search = (props: IconProps) => <Icon {...props} name="search" />;
export const Sessions = (props: IconProps) => <Icon {...props} name="sessions" />;
export const Settings = (props: IconProps) => <Icon {...props} name="settings" />;
export const SortUnsorted = (props: IconProps) => <Icon {...props} name="sort-unsorted" />;
export const Sun = (props: IconProps) => <Icon {...props} name="sun" />;
export const XCircle = (props: IconProps) => <Icon {...props} name="x-circle" />;
